import type { Question } from "./types";

/** Extra items so every track has 15 diagnostic questions. */
export const extraQuestionsByTrack: Record<string, Question[]> = {
  "python-fundamentals": [
    {
      id: "pf11",
      prompt: "What is printed?",
      code: "x = '3'\ny = 2\nprint(x * y)",
      options: ["6", "32", "33", "Error"],
      correctIndex: 2,
      skillIds: ["variables", "types"],
      explanation: "String * int repeats the string: '3' * 2 → '33'.",
      whyWrong: "Numeric multiply needs both sides as numbers. Here x is a string.",
    },
    {
      id: "pf12",
      prompt: "def f(a=2, b=3): return a*b — what is f(4)?",
      options: ["6", "12", "4", "Error"],
      correctIndex: 1,
      skillIds: ["functions", "params"],
      explanation: "a becomes 4, b stays default 3 → 12.",
      whyWrong: "Missing args use defaults; only a was overridden.",
    },
    {
      id: "pf13",
      prompt: "Which check is True for n = 0?",
      options: ["n", "not n", "n == False is invalid", "n > 0"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "0 is falsy, so not n is True.",
      whyWrong: "Truthy checks treat 0 as false in boolean context.",
    },
    {
      id: "pf14",
      prompt: "How many times does the body run?",
      code: "i = 5\nwhile i > 0:\n    i -= 2",
      options: ["2", "3", "5", "Infinite"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "i goes 5→3→1→-1. Body runs three times.",
      whyWrong: "The update changes i each pass until the condition fails.",
    },
    {
      id: "pf15",
      prompt: "Output of nested loops?",
      code: "c = 0\nfor a in range(2):\n  for b in range(2):\n    c += 1\nprint(c)",
      options: ["2", "3", "4", "8"],
      correctIndex: 2,
      skillIds: ["loops", "nested-loops"],
      explanation: "2 × 2 = 4 increments.",
      whyWrong: "Multiply outer and inner iterations.",
    },
  ],
  "js-foundations": [
    {
      id: "js11",
      prompt: "What is typeof null in JavaScript?",
      options: ["null", "undefined", "object", "boolean"],
      correctIndex: 2,
      skillIds: ["variables", "types"],
      explanation: "Historical quirk: typeof null === 'object'.",
      whyWrong: "null is a primitive, but typeof reports object.",
    },
    {
      id: "js12",
      prompt: "const add = (a,b) => a+b; add(2,3) returns?",
      options: ["undefined", "5", "23", "NaN"],
      correctIndex: 1,
      skillIds: ["functions", "params"],
      explanation: "Arrow function returns the sum 5.",
      whyWrong: "Expression-body arrows implicitly return the expression.",
    },
    {
      id: "js13",
      prompt: "Which is true for x = ''?",
      options: ["Boolean(x) === true", "!x === true", "x == true", "x === 0"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "Empty string is falsy, so !x is true.",
      whyWrong: "Empty string is falsy in boolean contexts.",
    },
    {
      id: "js14",
      prompt: "How many iterations?",
      code: "let n=0; for(let i=10;i>0;i-=3) n++;",
      options: ["3", "4", "10", "Infinite"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "i: 10,7,4,1 → four passes.",
      whyWrong: "Stop when i is no longer > 0 after updates of -3.",
    },
    {
      id: "js15",
      prompt: "Count of logs?",
      code: "for(let i=0;i<3;i++){ for(let j=0;j<1;j++) console.log(i,j); }",
      options: ["1", "2", "3", "4"],
      correctIndex: 2,
      skillIds: ["loops", "nested-loops"],
      explanation: "Outer 3 × inner 1 = 3 logs.",
      whyWrong: "Multiply the loop counts.",
    },
  ],
  "html-css": [
    {
      id: "hc11",
      prompt: "Which attribute links a CSS file?",
      options: ["<script src>", "<link rel='stylesheet' href='...'>", "<style src>", "<css href>"],
      correctIndex: 1,
      skillIds: ["html-structure"],
      explanation: "link with rel=stylesheet loads external CSS.",
      whyWrong: "script is for JS. style embeds CSS inline.",
    },
    {
      id: "hc12",
      prompt: "Best tag for the primary page heading?",
      options: ["<h1>", "<h6>", "<bold>", "<title> in body"],
      correctIndex: 0,
      skillIds: ["semantics"],
      explanation: "One clear h1 for the main title.",
      whyWrong: "title belongs in head; bold is presentational.",
    },
    {
      id: "hc13",
      prompt: "Selector for id main?",
      options: [".main", "#main", "main[]", "*main"],
      correctIndex: 1,
      skillIds: ["css-selectors"],
      explanation: "# targets an id.",
      whyWrong: "Dot is for classes.",
    },
    {
      id: "hc14",
      prompt: "box-sizing: border-box makes width include:",
      options: ["Only content", "Content + padding + border", "Only margin", "Only outline"],
      correctIndex: 1,
      skillIds: ["box-model"],
      explanation: "border-box folds padding and border into the set width.",
      whyWrong: "content-box adds padding/border outside the width.",
    },
    {
      id: "hc15",
      prompt: "flex-direction: column; main axis is:",
      options: ["Horizontal", "Vertical", "Diagonal", "Z-axis"],
      correctIndex: 1,
      skillIds: ["layout", "responsive"],
      explanation: "Column stacks items top to bottom — vertical main axis.",
      whyWrong: "Row is horizontal main axis.",
    },
  ],
  "sql-basics": [
    {
      id: "sq11",
      prompt: "ORDER BY salary DESC sorts:",
      options: ["Ascending", "Highest salary first", "Random", "By name"],
      correctIndex: 1,
      skillIds: ["select"],
      explanation: "DESC puts largest values first.",
      whyWrong: "ASC is ascending; DESC is descending.",
    },
    {
      id: "sq12",
      prompt: "WHERE name LIKE 'A%' matches:",
      options: ["Names ending with A", "Names starting with A", "Exact 'A%'", "Null names"],
      correctIndex: 1,
      skillIds: ["where"],
      explanation: "% is a wildcard; A% means starts with A.",
      whyWrong: "%A would mean ends with A.",
    },
    {
      id: "sq13",
      prompt: "LEFT JOIN keeps:",
      options: [
        "Only matches",
        "All left rows, matched right or null",
        "All right rows only",
        "Cartesian product only",
      ],
      correctIndex: 1,
      skillIds: ["joins"],
      explanation: "Left rows always appear; missing right side is null.",
      whyWrong: "INNER JOIN drops non-matches.",
    },
    {
      id: "sq14",
      prompt: "SUM(price) returns:",
      options: ["Row count", "Total of price values", "Average price", "Max price"],
      correctIndex: 1,
      skillIds: ["aggregates"],
      explanation: "SUM adds numeric values in the group.",
      whyWrong: "COUNT counts rows; AVG averages.",
    },
    {
      id: "sq15",
      prompt: "SELECT dept, AVG(sal) FROM emp GROUP BY dept HAVING AVG(sal) > 50k filters:",
      options: ["Rows before group", "Departments after aggregate", "Columns only", "Indexes"],
      correctIndex: 1,
      skillIds: ["group-by", "aggregates"],
      explanation: "HAVING filters groups using aggregate results.",
      whyWrong: "WHERE cannot use AVG directly on groups.",
    },
  ],
  "dsa-essentials": [
    {
      id: "ds11",
      prompt: "Inserting at the end of a dynamic array is amortized:",
      options: ["O(n²)", "O(1)", "O(n log n)", "O(log n) always worst"],
      correctIndex: 1,
      skillIds: ["arrays", "complexity"],
      explanation: "Amortized append is O(1) despite occasional resizes.",
      whyWrong: "Worst single resize can be O(n), amortized still O(1).",
    },
    {
      id: "ds12",
      prompt: "Valid indices for length 3 are:",
      options: ["1,2,3", "0,1,2", "0,1,2,3", "-1,0,1"],
      correctIndex: 1,
      skillIds: ["indexing"],
      explanation: "Zero-based: 0..2.",
      whyWrong: "Index 3 is out of range for length 3.",
    },
    {
      id: "ds13",
      prompt: "Undo history is best modeled with a:",
      options: ["Queue", "Stack", "Hash set", "Heap only"],
      correctIndex: 1,
      skillIds: ["stacks"],
      explanation: "Last action undone first → LIFO stack.",
      whyWrong: "Queues serve the oldest item first.",
    },
    {
      id: "ds14",
      prompt: "Print-job waiting line is a:",
      options: ["Stack", "Queue", "Graph", "Tree only"],
      correctIndex: 1,
      skillIds: ["queues"],
      explanation: "First submitted job prints first → FIFO.",
      whyWrong: "Stacks reverse order.",
    },
    {
      id: "ds15",
      prompt: "Visiting every node of a linked list once is:",
      options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
      correctIndex: 2,
      skillIds: ["traversal", "complexity"],
      explanation: "One pass over n nodes is linear.",
      whyWrong: "You cannot finish all nodes in constant time.",
    },
  ],
  "git-basics": [
    {
      id: "gt11",
      prompt: "git log shows:",
      options: ["Only untracked files", "Commit history", "npm packages", "CSS rules"],
      correctIndex: 1,
      skillIds: ["commits"],
      explanation: "log lists commits on the current history.",
      whyWrong: "status shows working tree; log shows history.",
    },
    {
      id: "gt12",
      prompt: "git restore --staged file mainly:",
      options: ["Deletes remote", "Unstages the file", "Creates a branch", "Force pushes"],
      correctIndex: 1,
      skillIds: ["staging"],
      explanation: "It removes the file from the index/staging area.",
      whyWrong: "It does not delete the branch or remote.",
    },
    {
      id: "gt13",
      prompt: "git branch -d feature deletes:",
      options: ["The remote repo", "A local branch", "All commits forever always", "Git itself"],
      correctIndex: 1,
      skillIds: ["branches"],
      explanation: "Deletes the local branch pointer (if merged).",
      whyWrong: "Remote branches need push delete separately.",
    },
    {
      id: "gt14",
      prompt: "Conflict markers look like:",
      options: ["TODO only", "<<<<< / ===== / >>>>>", "HTML comments", "JSON braces"],
      correctIndex: 1,
      skillIds: ["conflicts"],
      explanation: "Git inserts those markers around conflicting hunks.",
      whyWrong: "You edit the file to keep the correct final content.",
    },
    {
      id: "gt15",
      prompt: "git fetch without merge:",
      options: [
        "Updates remote-tracking refs only",
        "Always rewrites main",
        "Deletes local changes",
        "Publishes commits",
      ],
      correctIndex: 0,
      skillIds: ["remote"],
      explanation: "fetch downloads refs; pull = fetch + integrate.",
      whyWrong: "fetch alone does not merge into your branch.",
    },
  ],
};
