import type { Question } from "./types";
import { extraQuestionsByTrack } from "./extra-questions";

const baseQuestionsByTrack: Record<string, Question[]> = {
  "python-fundamentals": [
    {
      id: "pf1",
      prompt: "What is the value of x after this code runs?",
      code: "x = 4\nx = x + 2\nprint(x)",
      options: ["4", "6", "2", "x + 2"],
      correctIndex: 1,
      skillIds: ["variables"],
      explanation: "x starts at 4, then is reassigned to 4 + 2, so it becomes 6.",
      whyWrong: "The original value is overwritten. Assignment replaces the previous value.",
    },
    {
      id: "pf2",
      prompt: "Which statement correctly converts the string '12' into an integer?",
      options: ["str(12)", "int('12')", "float('12') only", "print('12')"],
      correctIndex: 1,
      skillIds: ["variables", "types"],
      explanation: "int('12') parses the numeric string into the integer 12.",
      whyWrong: "str() goes the other direction. print() only displays a value.",
    },
    {
      id: "pf3",
      prompt: "What does this function return?",
      code: "def add(a, b):\n    return a + b\n\nresult = add(3, 5)",
      options: ["None", "8", "35", "add"],
      correctIndex: 1,
      skillIds: ["functions", "params"],
      explanation: "The function returns the sum of its parameters: 3 + 5 = 8.",
      whyWrong: "Without return, a function yields None. Here return is present, so the sum is sent back.",
    },
    {
      id: "pf4",
      prompt: "What is printed?",
      code: "def greet(name):\n    print('Hi')\n\ngreet('Ava')",
      options: ["Hi Ava", "Hi", "Ava", "None"],
      correctIndex: 1,
      skillIds: ["functions", "params"],
      explanation: "The parameter is unused. The function always prints 'Hi'.",
      whyWrong: "Passing an argument does not automatically include it in output unless the function uses it.",
    },
    {
      id: "pf5",
      prompt: "Which condition is True when score is 70?",
      code: "score = 70",
      options: ["score > 70", "score >= 70", "score < 70", "score == 7"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "70 is not greater than 70, but it is greater than or equal to 70.",
      whyWrong: "Strict greater-than excludes equality. Boundary values need >= or <=.",
    },
    {
      id: "pf6",
      prompt: "What prints?",
      code: "n = 5\nif n % 2 == 0:\n    print('even')\nelse:\n    print('odd')",
      options: ["even", "odd", "5", "nothing"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "5 modulo 2 is 1, not 0, so the else branch runs.",
      whyWrong: "n % 2 == 0 tests evenness. Odd numbers take the else path.",
    },
    {
      id: "pf7",
      prompt: "How many times does this loop print?",
      code: "for i in range(3):\n    print(i)",
      options: ["2", "3", "4", "Infinite"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "range(3) yields 0, 1, 2 — three values.",
      whyWrong: "range(n) starts at 0 and stops before n. It does not include n itself.",
    },
    {
      id: "pf8",
      prompt: "What is the final value of total?",
      code: "total = 0\nfor i in range(1, 4):\n    total = total + i",
      options: ["3", "4", "6", "10"],
      correctIndex: 2,
      skillIds: ["loops", "loop-logic"],
      explanation: "Adds 1 + 2 + 3. range(1, 4) stops before 4, so total is 6.",
      whyWrong: "The stop value in range is exclusive. 4 is never added.",
    },
    {
      id: "pf9",
      prompt: "When does this loop stop?",
      code: "x = 0\nwhile x < 3:\n    x = x + 1",
      options: ["When x is 0", "When x becomes 3", "Never", "After one pass"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "The loop continues while x < 3. After x becomes 3, the condition fails.",
      whyWrong: "The update step is required. Without changing x, a while loop can run forever.",
    },
    {
      id: "pf10",
      prompt: "How many times does print run?",
      code: "for i in range(2):\n    for j in range(3):\n        print(i, j)",
      options: ["2", "3", "5", "6"],
      correctIndex: 3,
      skillIds: ["loops", "nested-loops", "loop-logic"],
      explanation: "Outer loop runs twice, inner loop three times each: 2 × 3 = 6 prints.",
      whyWrong: "Nested loops multiply iterations. Inner body runs for every pair (i, j).",
    },
  ],
  "js-foundations": [
    {
      id: "js1",
      prompt: "What is the value of count?",
      code: "let count = 1;\ncount = count + 3;",
      options: ["1", "3", "4", "undefined"],
      correctIndex: 2,
      skillIds: ["variables"],
      explanation: "count is reassigned to 1 + 3, which is 4.",
      whyWrong: "let allows reassignment. The first value is replaced, not stacked as a string.",
    },
    {
      id: "js2",
      prompt: "What does typeof '42' return?",
      options: ["number", "string", "boolean", "object"],
      correctIndex: 1,
      skillIds: ["variables", "types"],
      explanation: "Quoted 42 is a string, even if it looks numeric.",
      whyWrong: "Quotes make a string. Number conversion requires Number() or parseInt().",
    },
    {
      id: "js3",
      prompt: "What does this function return?",
      code: "function double(n) {\n  return n * 2;\n}\ndouble(6);",
      options: ["6", "12", "undefined", "n * 2"],
      correctIndex: 1,
      skillIds: ["functions", "params"],
      explanation: "6 * 2 is returned as 12.",
      whyWrong: "A missing return would yield undefined. This function does return a value.",
    },
    {
      id: "js4",
      prompt: "What is logged?",
      code: "function label(id) {\n  console.log('item');\n}\nlabel(9);",
      options: ["item 9", "9", "item", "undefined"],
      correctIndex: 2,
      skillIds: ["functions", "params"],
      explanation: "id is never used, so only 'item' is logged.",
      whyWrong: "Parameters only appear in output if the function body interpolates them.",
    },
    {
      id: "js5",
      prompt: "Which check is true when age is 18?",
      code: "const age = 18;",
      options: ["age > 18", "age >= 18", "age < 18", "age === '18'"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "18 is not greater than 18, but it is greater than or equal to 18.",
      whyWrong: "=== '18' fails because types differ. Boundary checks should use >=.",
    },
    {
      id: "js6",
      prompt: "What is logged?",
      code: "const n = 7;\nif (n % 2 === 0) {\n  console.log('even');\n} else {\n  console.log('odd');\n}",
      options: ["even", "odd", "7", "nothing"],
      correctIndex: 1,
      skillIds: ["conditions"],
      explanation: "7 is odd, so the else branch runs.",
      whyWrong: "Remainder 0 means even. Odd numbers take the else path.",
    },
    {
      id: "js7",
      prompt: "How many times does this loop run?",
      code: "for (let i = 0; i < 4; i++) {\n  console.log(i);\n}",
      options: ["3", "4", "5", "Infinite"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "i goes 0, 1, 2, 3 — four iterations. It stops when i is 4.",
      whyWrong: "The loop runs while i < 4, not until i equals 4 inside the body count as extra.",
    },
    {
      id: "js8",
      prompt: "What is the final value of sum?",
      code: "let sum = 0;\nfor (let i = 1; i <= 3; i++) {\n  sum += i;\n}",
      options: ["3", "6", "4", "0"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "Adds 1 + 2 + 3 because the condition is i <= 3.",
      whyWrong: "<= includes the end value. < would have stopped before 3.",
    },
    {
      id: "js9",
      prompt: "When does this while loop stop?",
      code: "let x = 0;\nwhile (x < 2) {\n  x += 1;\n}",
      options: ["When x is 0", "When x becomes 2", "Never", "Immediately"],
      correctIndex: 1,
      skillIds: ["loops", "loop-logic"],
      explanation: "x increases until it is 2, then x < 2 is false.",
      whyWrong: "If x never changes, the loop never ends. The increment is what creates an exit.",
    },
    {
      id: "js10",
      prompt: "How many logs are produced?",
      code: "for (let i = 0; i < 2; i++) {\n  for (let j = 0; j < 2; j++) {\n    console.log(i, j);\n  }\n}",
      options: ["2", "3", "4", "8"],
      correctIndex: 2,
      skillIds: ["loops", "nested-loops", "loop-logic"],
      explanation: "2 outer × 2 inner = 4 logs.",
      whyWrong: "Nested loops multiply. Each outer pass runs the full inner loop.",
    },
  ],
  "html-css": [
    {
      id: "hc1",
      prompt: "Which tag wraps the main visible content of a page?",
      options: ["<head>", "<body>", "<meta>", "<title>"],
      correctIndex: 1,
      skillIds: ["html-structure"],
      explanation: "<body> holds content users see. <head> holds metadata.",
      whyWrong: "<head> is for title, links, and scripts — not page body content.",
    },
    {
      id: "hc2",
      prompt: "Which structure is valid nesting?",
      code: "A) <p><div>text</div></p>\nB) <div><p>text</p></div>",
      options: ["Only A", "Only B", "Both", "Neither"],
      correctIndex: 1,
      skillIds: ["html-structure"],
      explanation: "Block <div> should not sit inside <p>. Put paragraphs inside divs.",
      whyWrong: "Browsers auto-close <p> when a block tag appears inside it.",
    },
    {
      id: "hc3",
      prompt: "Best semantic choice for site navigation links?",
      options: ["<div class='nav'>", "<nav>", "<span>", "<section>"],
      correctIndex: 1,
      skillIds: ["html-structure", "semantics"],
      explanation: "<nav> tells browsers and assistive tech that the block is navigation.",
      whyWrong: "A styled div is presentational. Semantics need the right tag.",
    },
    {
      id: "hc4",
      prompt: "Which selector targets only elements with class card?",
      options: ["#card", "card", ".card", "card[]"],
      correctIndex: 2,
      skillIds: ["css-selectors"],
      explanation: "A leading dot means class. # is id.",
      whyWrong: "Without a dot, CSS looks for a tag named card, which is wrong here.",
    },
    {
      id: "hc5",
      prompt: "In the box model, which sits between border and content?",
      options: ["Margin", "Padding", "Outline", "Gap"],
      correctIndex: 1,
      skillIds: ["css-selectors", "box-model"],
      explanation: "Padding is inside the border. Margin is outside.",
      whyWrong: "Margin pushes other elements away; padding pads inside the box.",
    },
    {
      id: "hc6",
      prompt: "Total width with content 200px, padding 10px each side, border 1px each side (content-box)?",
      options: ["200px", "220px", "222px", "211px"],
      correctIndex: 2,
      skillIds: ["box-model"],
      explanation: "200 + 20 padding + 2 border = 222.",
      whyWrong: "content-box adds padding and border on top of content width.",
    },
    {
      id: "hc7",
      prompt: "display: flex; justify-content: space-between; mainly controls:",
      options: ["Font size", "Main-axis spacing", "Z-index", "Border radius"],
      correctIndex: 1,
      skillIds: ["layout"],
      explanation: "justify-content distributes items along the main axis.",
      whyWrong: "Cross-axis alignment is align-items, not justify-content.",
    },
    {
      id: "hc8",
      prompt: "CSS Grid places items into:",
      options: ["Only columns", "Only rows", "Rows and columns", "A single stack"],
      correctIndex: 2,
      skillIds: ["layout"],
      explanation: "Grid is two-dimensional: rows and columns.",
      whyWrong: "Flex is mainly one axis; Grid is designed for both axes.",
    },
    {
      id: "hc9",
      prompt: "Which media query targets screens up to 600px wide?",
      options: [
        "@media (min-width: 600px)",
        "@media (max-width: 600px)",
        "@media screen 600",
        "@media width=600",
      ],
      correctIndex: 1,
      skillIds: ["layout", "responsive"],
      explanation: "max-width applies when the viewport is at most 600px.",
      whyWrong: "min-width applies from that size and larger.",
    },
    {
      id: "hc10",
      prompt: "A fluid layout usually prefers:",
      options: ["Fixed px only", "% / fr / rem with breakpoints", "Absolute positioning only", "Tables for everything"],
      correctIndex: 1,
      skillIds: ["responsive"],
      explanation: "Relative units plus breakpoints adapt across devices.",
      whyWrong: "Hard-coded pixels break on small and large screens.",
    },
  ],
  "sql-basics": [
    {
      id: "sq1",
      prompt: "Which query returns every column from users?",
      options: ["GET * FROM users", "SELECT * FROM users", "FIND users ALL", "SHOW users"],
      correctIndex: 1,
      skillIds: ["select"],
      explanation: "SELECT * FROM table is the standard full-column read.",
      whyWrong: "SQL uses SELECT, not GET or FIND, for reading rows.",
    },
    {
      id: "sq2",
      prompt: "To return only the name column:",
      options: ["SELECT name FROM users", "SELECT * name users", "PICK name users", "SELECT users.name ONLY"],
      correctIndex: 0,
      skillIds: ["select"],
      explanation: "List the columns after SELECT, then FROM the table.",
      whyWrong: "Column names go in the SELECT list, not after a wildcard mashup.",
    },
    {
      id: "sq3",
      prompt: "Rows where age is greater than 18:",
      options: [
        "SELECT * FROM users FILTER age > 18",
        "SELECT * FROM users WHERE age > 18",
        "SELECT * FROM users HAVING age > 18",
        "SELECT * FROM users IF age > 18",
      ],
      correctIndex: 1,
      skillIds: ["select", "where"],
      explanation: "WHERE filters rows before grouping.",
      whyWrong: "HAVING filters after GROUP BY. Row filters belong in WHERE.",
    },
    {
      id: "sq4",
      prompt: "WHERE city = 'Delhi' AND active = 1 means:",
      options: ["Either condition", "Both conditions", "Only city", "Only active"],
      correctIndex: 1,
      skillIds: ["where"],
      explanation: "AND requires every listed condition to be true.",
      whyWrong: "OR would accept either condition.",
    },
    {
      id: "sq5",
      prompt: "INNER JOIN returns rows when:",
      options: [
        "They exist only in the left table",
        "They match on the join key in both tables",
        "They exist only in the right table",
        "Always every combination",
      ],
      correctIndex: 1,
      skillIds: ["joins", "inner-join"],
      explanation: "INNER JOIN keeps matches present in both sides.",
      whyWrong: "LEFT JOIN keeps all left rows even without a match.",
    },
    {
      id: "sq6",
      prompt: "Typical join condition looks like:",
      options: [
        "ON users.id = orders.user_id",
        "WHERE users = orders",
        "JOIN BY name",
        "LINK users orders",
      ],
      correctIndex: 0,
      skillIds: ["joins", "inner-join"],
      explanation: "ON compares the foreign key to the primary key.",
      whyWrong: "Joins need an explicit key relationship, not table-name equality.",
    },
    {
      id: "sq7",
      prompt: "COUNT(*) counts:",
      options: ["Distinct columns only", "Rows in the result group", "Nulls only", "Indexes"],
      correctIndex: 1,
      skillIds: ["aggregates"],
      explanation: "COUNT(*) tallies rows, including those with nulls in other columns.",
      whyWrong: "COUNT(column) skips nulls in that column; COUNT(*) counts rows.",
    },
    {
      id: "sq8",
      prompt: "To get average salary by department you need:",
      options: ["WHERE only", "GROUP BY department", "ORDER BY only", "LIMIT only"],
      correctIndex: 1,
      skillIds: ["aggregates", "group-by"],
      explanation: "GROUP BY splits rows into department buckets, then AVG runs per bucket.",
      whyWrong: "WHERE filters rows; it does not create aggregate groups.",
    },
    {
      id: "sq9",
      prompt: "After GROUP BY city, filtering cities with COUNT(*) > 5 uses:",
      options: ["WHERE COUNT(*) > 5", "HAVING COUNT(*) > 5", "IF COUNT(*) > 5", "FILTER COUNT(*) > 5"],
      correctIndex: 1,
      skillIds: ["group-by"],
      explanation: "HAVING filters groups after aggregation.",
      whyWrong: "WHERE cannot use aggregate results like COUNT(*).",
    },
    {
      id: "sq10",
      prompt: "SELECT name, COUNT(*) FROM users GROUP BY name is valid because:",
      options: [
        "name is aggregated",
        "non-aggregated columns appear in GROUP BY",
        "COUNT is optional",
        "SQL ignores GROUP BY",
      ],
      correctIndex: 1,
      skillIds: ["group-by", "aggregates"],
      explanation: "Selected non-aggregate columns must be in GROUP BY.",
      whyWrong: "Mixing free columns with aggregates without GROUP BY is invalid.",
    },
  ],
  "dsa-essentials": [
    {
      id: "ds1",
      prompt: "In a zero-based array of length 5, the last index is:",
      options: ["5", "4", "0", "6"],
      correctIndex: 1,
      skillIds: ["arrays", "indexing"],
      explanation: "Indices run 0..n-1, so length 5 ends at index 4.",
      whyWrong: "Using n as an index is the classic off-by-one bug.",
    },
    {
      id: "ds2",
      prompt: "Accessing arr[i] in a contiguous array is usually:",
      options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
      correctIndex: 1,
      skillIds: ["arrays", "complexity"],
      explanation: "Index math jumps straight to the slot — constant time.",
      whyWrong: "Scanning for a value is O(n); indexed access is O(1).",
    },
    {
      id: "ds3",
      prompt: "Stack order is:",
      options: ["FIFO", "LIFO", "Sorted", "Random"],
      correctIndex: 1,
      skillIds: ["stacks"],
      explanation: "Last in, first out — like a stack of plates.",
      whyWrong: "Queues are FIFO. Stacks reverse the most recent push.",
    },
    {
      id: "ds4",
      prompt: "After push(1), push(2), pop(), the stack top is:",
      options: ["1", "2", "empty", "3"],
      correctIndex: 0,
      skillIds: ["stacks"],
      explanation: "Pop removes 2; 1 remains on top.",
      whyWrong: "Pop removes the newest value, not the oldest.",
    },
    {
      id: "ds5",
      prompt: "Queue order is:",
      options: ["LIFO", "FIFO", "Priority only", "Circular only"],
      correctIndex: 1,
      skillIds: ["queues"],
      explanation: "First in, first out — like a ticket line.",
      whyWrong: "Dequeuing removes from the front, not the back.",
    },
    {
      id: "ds6",
      prompt: "enqueue(A), enqueue(B), dequeue() returns:",
      options: ["B", "A", "AB", "empty"],
      correctIndex: 1,
      skillIds: ["queues"],
      explanation: "A entered first, so A leaves first.",
      whyWrong: "Returning B would be stack behavior.",
    },
    {
      id: "ds7",
      prompt: "Nested loops over n and n are typically:",
      options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
      correctIndex: 2,
      skillIds: ["complexity"],
      explanation: "n × n iterations grow quadratically.",
      whyWrong: "One loop is O(n). Two nested n-loops multiply.",
    },
    {
      id: "ds8",
      prompt: "Binary search on a sorted array is:",
      options: ["O(n)", "O(n²)", "O(log n)", "O(2ⁿ)"],
      correctIndex: 2,
      skillIds: ["complexity", "traversal"],
      explanation: "Each step halves the search space.",
      whyWrong: "Linear scan is O(n). Sorted + halving gives log n.",
    },
    {
      id: "ds9",
      prompt: "Traversing each array element once is:",
      options: ["O(1)", "O(n)", "O(n log n)", "O(n²)"],
      correctIndex: 1,
      skillIds: ["arrays", "traversal"],
      explanation: "One visit per element scales with length n.",
      whyWrong: "Constant time cannot grow with input size.",
    },
    {
      id: "ds10",
      prompt: "A common traversal bug is:",
      options: ["Using i < n", "Starting at 0", "Using i <= n on 0..n-1", "Reading arr[0]"],
      correctIndex: 2,
      skillIds: ["indexing", "traversal"],
      explanation: "i <= n reads one past the end on a length-n array.",
      whyWrong: "The valid last index is n-1, so the test should be i < n.",
    },
  ],
  "git-basics": [
    {
      id: "gt1",
      prompt: "A commit is best described as:",
      options: ["A temporary undo", "A snapshot with a message", "A remote server", "A branch lock"],
      correctIndex: 1,
      skillIds: ["commits"],
      explanation: "Each commit records project state plus metadata.",
      whyWrong: "Commits are durable history points, not just undo buttons.",
    },
    {
      id: "gt2",
      prompt: "git add prepares files for:",
      options: ["Push only", "The next commit", "Deleting remotes", "Creating tags only"],
      correctIndex: 1,
      skillIds: ["commits", "staging"],
      explanation: "Staging selects what the next commit will include.",
      whyWrong: "Unstaged changes stay out of the commit.",
    },
    {
      id: "gt3",
      prompt: "git status shows:",
      options: ["Only remote URLs", "Working tree and staging state", "CI logs", "Only old tags"],
      correctIndex: 1,
      skillIds: ["staging"],
      explanation: "Status lists modified, staged, and untracked files.",
      whyWrong: "Remotes are inspected with remote -v, not status alone.",
    },
    {
      id: "gt4",
      prompt: "A branch is:",
      options: ["A copy of GitHub", "A movable pointer to commits", "A deleted file", "A force-push"],
      correctIndex: 1,
      skillIds: ["branches"],
      explanation: "Branches point at commits so work can diverge safely.",
      whyWrong: "Creating a branch does not duplicate the whole remote.",
    },
    {
      id: "gt5",
      prompt: "To switch branches:",
      options: ["git move", "git switch / git checkout", "git jump", "git remote"],
      correctIndex: 1,
      skillIds: ["branches"],
      explanation: "switch/checkout updates HEAD to another branch.",
      whyWrong: "remote manages remotes; it does not change branches.",
    },
    {
      id: "gt6",
      prompt: "git merge feature combines feature into:",
      options: ["A random commit", "The current branch", "Only origin/main always", "The stash"],
      correctIndex: 1,
      skillIds: ["branches", "merge"],
      explanation: "Merge applies the other branch into whatever you are on now.",
      whyWrong: "Always check the current branch before merging.",
    },
    {
      id: "gt7",
      prompt: "A merge conflict happens when:",
      options: [
        "Two edits change the same region differently",
        "You commit once",
        "The repo is private",
        "You use HTTPS",
      ],
      correctIndex: 0,
      skillIds: ["merge", "conflicts"],
      explanation: "Git cannot auto-choose between conflicting hunks.",
      whyWrong: "Privacy and protocol do not create content conflicts.",
    },
    {
      id: "gt8",
      prompt: "After resolving conflict markers you should:",
      options: ["Delete .git", "Stage and commit the merge", "Only pull again", "Force reboot"],
      correctIndex: 1,
      skillIds: ["conflicts"],
      explanation: "Mark files resolved with add, then complete the merge commit.",
      whyWrong: "Leaving conflicts unstaged keeps the merge unfinished.",
    },
    {
      id: "gt9",
      prompt: "git push sends commits to:",
      options: ["Only local stash", "The configured remote", "npm registry", "Browser cache"],
      correctIndex: 1,
      skillIds: ["remote"],
      explanation: "Push publishes local commits to origin (or another remote).",
      whyWrong: "Local-only commits stay invisible to teammates until push.",
    },
    {
      id: "gt10",
      prompt: "git pull typically:",
      options: [
        "Deletes branches",
        "Fetches and integrates remote updates",
        "Creates a new repo",
        "Removes staging",
      ],
      correctIndex: 1,
      skillIds: ["remote"],
      explanation: "Pull updates your branch from the remote tracking branch.",
      whyWrong: "Pull syncs history; it is not a repo initializer.",
    },
  ],
};

export const questionsByTrack: Record<string, Question[]> = Object.fromEntries(
  Object.keys(baseQuestionsByTrack).map((id) => [
    id,
    [...(baseQuestionsByTrack[id] ?? []), ...(extraQuestionsByTrack[id] ?? [])],
  ])
);

export const practiceBank: Record<string, { prompt: string; hint: string; answer: string }[]> = {
  variables: [
    { prompt: "Trace: a = 2; a = a * 5. What is a?", hint: "Reassignment replaces the old value.", answer: "10" },
    { prompt: "Which keyword creates a reassignable JS variable: const or let?", hint: "const cannot be reassigned.", answer: "let" },
  ],
  types: [
    { prompt: "Is '8' a number or a string in Python/JS literals?", hint: "Quotes decide the type.", answer: "string" },
    { prompt: "What does int('9') produce in Python?", hint: "Parsing a numeric string.", answer: "9" },
  ],
  functions: [
    { prompt: "If a function has no return, what does it yield in Python?", hint: "The implicit return.", answer: "None" },
    { prompt: "True or false: a parameter exists only if the function uses it in output.", hint: "Parameters exist even if unused.", answer: "false" },
  ],
  params: [
    { prompt: "def f(n): return n. What is f(4)?", hint: "The argument is bound to n.", answer: "4" },
    { prompt: "function f(a,b){ return a; } What is f(1,9)?", hint: "Only a is returned.", answer: "1" },
  ],
  conditions: [
    { prompt: "Is 10 > 10 true?", hint: "Greater-than is strict.", answer: "no" },
    { prompt: "Which operator includes equality with greater: > or >= ?", hint: "Boundary checks.", answer: ">=" },
  ],
  loops: [
    { prompt: "How many values does range(4) yield?", hint: "0 through 3.", answer: "4" },
    { prompt: "for (i=0; i<3; i++) runs how many times?", hint: "0,1,2.", answer: "3" },
  ],
  "loop-logic": [
    { prompt: "range(1,5) includes 5? yes/no", hint: "Stop is exclusive.", answer: "no" },
    { prompt: "A while loop must change the tested variable. Why?", hint: "Otherwise the condition never flips.", answer: "to terminate" },
  ],
  "nested-loops": [
    { prompt: "Outer 3 × inner 2 = how many inner-body runs?", hint: "Multiply iterations.", answer: "6" },
    { prompt: "Does the inner loop restart on each outer pass? yes/no", hint: "Nested control flow.", answer: "yes" },
  ],
  "html-structure": [
    { prompt: "Visible page content lives in which tag?", hint: "Not head.", answer: "body" },
    { prompt: "Can a div sit inside a p? yes/no", hint: "Invalid nesting.", answer: "no" },
  ],
  semantics: [
    { prompt: "Best tag for navigation links?", hint: "Semantic HTML5.", answer: "nav" },
    { prompt: "Is a plain div semantic for a blog post body? yes/no", hint: "Prefer article/main.", answer: "no" },
  ],
  "css-selectors": [
    { prompt: "Class selector starts with?", hint: "Dot vs hash.", answer: "." },
    { prompt: "Id selector starts with?", hint: "Hash.", answer: "#" },
  ],
  "box-model": [
    { prompt: "Padding is inside or outside the border?", hint: "Inner spacing.", answer: "inside" },
    { prompt: "Margin is inside or outside the border?", hint: "Outer spacing.", answer: "outside" },
  ],
  layout: [
    { prompt: "justify-content aligns on which flex axis?", hint: "Main axis.", answer: "main" },
    { prompt: "Is CSS Grid one-dimensional? yes/no", hint: "Rows and columns.", answer: "no" },
  ],
  responsive: [
    { prompt: "max-width: 600px targets screens ___ 600px", hint: "Up to.", answer: "up to" },
    { prompt: "Prefer rem/% or only fixed px for fluid UI?", hint: "Relative units.", answer: "rem/%" },
  ],
  select: [
    { prompt: "Keyword to read rows in SQL?", hint: "Not GET.", answer: "SELECT" },
    { prompt: "SELECT * means?", hint: "Columns.", answer: "all columns" },
  ],
  where: [
    { prompt: "Row filters use WHERE or HAVING?", hint: "Before grouping.", answer: "WHERE" },
    { prompt: "AND means both conditions? yes/no", hint: "Boolean logic.", answer: "yes" },
  ],
  joins: [
    { prompt: "JOIN combines what?", hint: "Related tables.", answer: "tables" },
    { prompt: "Join keys are compared in ON or SELECT?", hint: "Join clause.", answer: "ON" },
  ],
  "inner-join": [
    { prompt: "INNER JOIN keeps unmatched left rows? yes/no", hint: "Matches only.", answer: "no" },
    { prompt: "users.id = orders.user_id is a typical?", hint: "Relationship.", answer: "join condition" },
  ],
  aggregates: [
    { prompt: "COUNT(*) counts?", hint: "Rows.", answer: "rows" },
    { prompt: "AVG is an?", hint: "Summary function.", answer: "aggregate" },
  ],
  "group-by": [
    { prompt: "Filter groups with COUNT use WHERE or HAVING?", hint: "After aggregate.", answer: "HAVING" },
    { prompt: "Non-aggregated SELECT columns must be in?", hint: "Grouping rule.", answer: "GROUP BY" },
  ],
  arrays: [
    { prompt: "First index in most languages?", hint: "Zero-based.", answer: "0" },
    { prompt: "arr[i] access is usually O(?)", hint: "Constant.", answer: "1" },
  ],
  indexing: [
    { prompt: "Length 5 array last index?", hint: "n-1.", answer: "4" },
    { prompt: "i <= n on 0..n-1 is safe? yes/no", hint: "Off-by-one.", answer: "no" },
  ],
  stacks: [
    { prompt: "Stack order acronym?", hint: "Last in…", answer: "LIFO" },
    { prompt: "pop removes from where?", hint: "Top.", answer: "top" },
  ],
  queues: [
    { prompt: "Queue order acronym?", hint: "First in…", answer: "FIFO" },
    { prompt: "dequeue removes from where?", hint: "Front.", answer: "front" },
  ],
  complexity: [
    { prompt: "Two nested n-loops ≈ O(?)", hint: "Quadratic.", answer: "n²" },
    { prompt: "Binary search ≈ O(?)", hint: "Halving.", answer: "log n" },
  ],
  traversal: [
    { prompt: "Visit each of n items once ≈ O(?)", hint: "Linear.", answer: "n" },
    { prompt: "Loop condition for 0..n-1?", hint: "Strict less.", answer: "i < n" },
  ],
  commits: [
    { prompt: "A commit stores a?", hint: "Project snapshot.", answer: "snapshot" },
    { prompt: "Commit messages should be?", hint: "Clear why.", answer: "descriptive" },
  ],
  staging: [
    { prompt: "git add affects?", hint: "Next commit.", answer: "staging area" },
    { prompt: "Command to inspect staged vs unstaged?", hint: "Common status cmd.", answer: "git status" },
  ],
  branches: [
    { prompt: "A branch points to?", hint: "Commit pointer.", answer: "commits" },
    { prompt: "Switch branches with?", hint: "switch/checkout.", answer: "git switch" },
  ],
  merge: [
    { prompt: "git merge applies into?", hint: "Current branch.", answer: "current branch" },
    { prompt: "Merge combines?", hint: "Histories.", answer: "histories" },
  ],
  conflicts: [
    { prompt: "Conflicts happen when edits overlap? yes/no", hint: "Same region.", answer: "yes" },
    { prompt: "After fixing markers, you must?", hint: "Stage + commit.", answer: "stage and commit" },
  ],
  remote: [
    { prompt: "git push updates the?", hint: "origin etc.", answer: "remote" },
    { prompt: "git pull fetches and?", hint: "Integrate.", answer: "integrates" },
  ],
};
